In [1]:
import tensorflow as tf
print (tf.__version__)

2.9.1


In [2]:
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
#check number of dimensions
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([3,3])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

In [5]:
#create a matrix 
matrix1 = tf.constant([[3,3],
                      [3,3]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]])>

In [6]:
#create matrix with dtype
matrix2= tf.constant([[3.3,3.3],
                      [3.3,3.3]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3.3, 3.3],
       [3.3, 3.3]], dtype=float16)>

In [7]:
#create 3x3 matrix
matrix3=tf.constant([[[3,3,3],
                      [3,3,3],
                      [3,3,3]]])
matrix3

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])>

In [8]:
#creating a tensor variable
var=tf.Variable([3,3])
const=tf.constant([3,3])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

In [9]:
rand1 = tf.random.Generator.from_seed(42)
rand1=rand1.uniform(shape=(3,2))
rand2= tf.random.Generator.from_seed(42)
rand2=rand2.uniform(shape=(3,2))
rand1,rand2,rand1==rand2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [10]:
not_shuffled = tf.constant([[3,3],
                            [3,4],
                            [3,5]])
                            
                            
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 4],
       [3, 5]])>

In [11]:
tf.random.set_seed(30)
tf.random.shuffle(not_shuffled, seed=20)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 4],
       [3, 5]])>

In [12]:
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros([3,3], tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [14]:
import numpy as np
n1=np.arange(1,28,dtype=np.int32)
A=tf.constant(n1,shape=(3,3,3))
A

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [15]:
#creatibg a rank 4 tensor
rank_4_t=tf.zeros(shape=[3,3,3,3])
rank_4_t

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [16]:
tf.size(rank_4_t).numpy()

81

In [17]:
#getting first two elements of tensor
rank_4_t[:2,:1]

<tf.Tensor: shape=(2, 1, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [18]:
#get first element from each dimension 
rank_4_t[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0., 0., 0.]]]], dtype=float32)>

In [19]:
rank_2_t=tf.constant([[3,1],
                      [3,2]])
rank_2_t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 1],
       [3, 2]])>

In [20]:
rank_2_t.shape, rank_2_t.ndim

(TensorShape([2, 2]), 2)

In [21]:
rank_3_t=rank_2_t[...,tf.newaxis]
rank_3_t

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [1]],

       [[3],
        [2]]])>

In [22]:
tf.expand_dims(rank_2_t,axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[3],
        [1]],

       [[3],
        [2]]])>

In [23]:
#manipulating tensors
t2=tf.constant([[3,3],[3,3]])
t2+10,t2-10,t2*10,t2/3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 13],
        [13, 13]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-7, -7],
        [-7, -7]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 30],
        [30, 30]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[1., 1.],
        [1., 1.]])>)

In [24]:
t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]])>

In [25]:
#matrix multiplication
t1=tf.constant([[3,3],[3,3]])
tf.linalg.matmul(t1,t2), t1@t2
 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[18, 18],
        [18, 18]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[18, 18],
        [18, 18]])>)

In [26]:
t3=tf.random.Generator.from_seed(100)
t3=t3.uniform(shape=(3,2))
t4=tf.random.Generator.from_seed(200)
t4=t4.normal(shape=(3,2))
t3,t4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.6661966 , 0.7469058 ],
        [0.8769325 , 0.8477416 ],
        [0.22709787, 0.49256873]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.83051693,  1.543791  ],
        [-0.5432179 ,  0.36891136],
        [ 1.6245334 , -0.9666689 ]], dtype=float32)>)

In [27]:
t4=tf.reshape(t4,shape=(2,3))
t4

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.83051693,  1.543791  , -0.5432179 ],
       [ 0.36891136,  1.6245334 , -0.9666689 ]], dtype=float32)>

In [28]:
t3@t4

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.27774554,  2.2418418 , -1.0839005 ],
       [-0.4155658 ,  2.7309852 , -1.2958509 ],
       [-0.00689444,  1.150786  , -0.5995145 ]], dtype=float32)>

In [29]:
t5=tf.random.Generator.from_seed(300)
t5=t5.uniform(shape=(3,2))
t5

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.00473952, 0.06306279],
       [0.91214204, 0.46108627],
       [0.17251897, 0.9006287 ]], dtype=float32)>

In [30]:
t5=tf.transpose(t5)
t5

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.00473952, 0.91214204, 0.17251897],
       [0.06306279, 0.46108627, 0.9006287 ]], dtype=float32)>

In [31]:
t3@t5

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.05025942, 0.9520539 , 0.7876163 ],
       [0.05761719, 1.190769  , 0.9147879 ],
       [0.03213909, 0.4342622 , 0.48280022]], dtype=float32)>

In [ ]:
tf.matmul(t3, tf.transpose(t4))

In [32]:
t6 = tf.constant([3.3,3.3])
t6

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.3, 3.3], dtype=float32)>

In [33]:
t6=tf.cast(t6, dtype= tf.float16)
t6

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.3, 3.3], dtype=float16)>

In [34]:
t7 = tf.constant([3,3])
t7

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

In [38]:
t7 = tf.cast(t7, dtype=tf.float16)
t7

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3., 3.], dtype=float16)>

In [40]:
#getting the absolute values
t8 = tf.constant([-3,-3])
t8, tf.abs(t8)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -3])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>)

In [41]:
#minimum of tensor
t9 = tf.constant(np.random.randint(0,100, size = 50))
t9, tf.reduce_min(t9)


(<tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([14, 16, 88, 75, 66, 77,  1, 33, 49, 19, 21, 60, 87, 72, 77, 67, 76,
        95, 90, 65,  9,  8,  9, 23, 97, 37, 97, 51, 53, 73, 58,  1, 12, 70,
        76, 97, 77, 64, 43, 27, 46, 14, 91, 74, 96, 50, 10, 93, 59, 18])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [43]:
#maximum of tensor
t10 = tf.constant(np.random.randint(0,300,size=100))
t10, tf.reduce_max(t10)

(<tf.Tensor: shape=(100,), dtype=int32, numpy=
 array([ 35, 219,  87,  57, 113, 286, 263,  49, 210, 169, 161, 232,  71,
         76,  91, 244,   8,  57, 294, 251, 209, 292,  80,  25,  83, 281,
         92, 267, 164,  25, 176,  86, 133,  26, 105, 246,  54, 186, 168,
         56, 285, 272, 196, 123,  77, 118, 195,   5, 279, 266,  82,  23,
        212, 205,  34, 226, 152,  54,  99, 202,  48, 109, 204, 275,  88,
        243, 134, 136,  34, 170,  33,  43,  21,  97,  81, 267, 219, 269,
        265,  29, 285, 203, 104, 186, 233,  15,  51,   6, 264, 186, 200,
        187, 212, 236, 261, 153, 223,  30, 275, 113])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=294>)

In [46]:
#sum of tensor
tf.reduce_sum(t10)

<tf.Tensor: shape=(), dtype=int32, numpy=15020>

In [48]:
#variance of tensor
import tensorflow_probability as tfp
tfp.stats.variance(t10)

ImportError: cannot import name 'tensorflow_probability' from 'tensorflow' (d:\Frameworks\Python\lib\site-packages\tensorflow\__init__.py)

In [ ]:
#standard deviation of tensor
tf.math.reduce_std(tf.cast(t10, dtype=)