In [1]:
import tensorflow as tf
print (tf.__version__)

2.9.1


In [2]:
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
#check number of dimensions
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([3,3])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

In [5]:
#create a matrix 
matrix1 = tf.constant([[3,3],
                      [3,3]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]])>

In [6]:
#create matrix with dtype
matrix2= tf.constant([[3.3,3.3],
                      [3.3,3.3]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3.3, 3.3],
       [3.3, 3.3]], dtype=float16)>

In [7]:
#create 3x3 matrix
matrix3=tf.constant([[[3,3,3],
                      [3,3,3],
                      [3,3,3]]])
matrix3

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])>

In [8]:
#creating a tensor variable
var=tf.Variable([3,3])
const=tf.constant([3,3])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

In [9]:
rand1 = tf.random.Generator.from_seed(42)
rand1=rand1.uniform(shape=(3,2))
rand2= tf.random.Generator.from_seed(42)
rand2=rand2.uniform(shape=(3,2))
rand1,rand2,rand1==rand2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [10]:
not_shuffled = tf.constant([[3,3],
                            [3,4],
                            [3,5]])
                            
                            
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 4],
       [3, 5]])>

In [11]:
tf.random.set_seed(30)
tf.random.shuffle(not_shuffled, seed=20)
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 4],
       [3, 5]])>

In [12]:
tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros([3,3], tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [14]:
import numpy as np
n1=np.arange(1,28,dtype=np.int32)
A=tf.constant(n1,shape=(3,3,3))
A

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])>

In [23]:
#creatibg a rank 4 tensor
rank_4_t=tf.zeros(shape=[3,3,3,3])
rank_4_t

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [24]:
tf.size(rank_4_t).numpy()

81

In [26]:
#getting first two elements of tensor
rank_4_t[:2,:1]

<tf.Tensor: shape=(2, 1, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [27]:
#get first element from each dimension 
rank_4_t[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_2_t=tf.constant([[3,1],
                      [3,2]])
rank_2_t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 1],
       [3, 2]])>

In [31]:
rank_2_t.shape, rank_2_t.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_3-t