In [1]:
import tensorflow as tf
print (tf.__version__)

2.9.1


In [2]:
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [3]:
#check number of dimensions
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([3,3])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>

In [5]:
#create a matrix 
matrix1 = tf.constant([[3,3],
                      [3,3]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]])>

In [6]:
#create matrix with dtype
matrix2= tf.constant([[3.3,3.3],
                      [3.3,3.3]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3.3, 3.3],
       [3.3, 3.3]], dtype=float16)>

In [7]:
#create 3x3 matrix
matrix3=tf.constant([[[3,3,3],
                      [3,3,3],
                      [3,3,3]]])
matrix3

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])>

In [9]:
#creating a tensor variable
var=tf.Variable([3,3])
const=tf.constant([3,3])