In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv('Data/medical_insurance.csv')
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
#one hot encoding
encoded_data=pd.get_dummies(data)
encoded_data

age     bmi  children      charges  sex_female  sex_male  smoker_no  \
0      19  27.900         0  16884.92400           1         0          0   
1      18  33.770         1   1725.55230           0         1          1   
2      28  33.000         3   4449.46200           0         1          1   
3      33  22.705         0  21984.47061           0         1          1   
4      32  28.880         0   3866.85520           0         1          1   
...   ...     ...       ...          ...         ...       ...        ...   
1333   50  30.970         3  10600.54830           0         1          1   
1334   18  31.920         0   2205.98080           1         0          1   
1335   18  36.850         0   1629.83350           1         0          1   
1336   21  25.800         0   2007.94500           1         0          1   
1337   61  29.070         0  29141.36030           1         0          0   

      smoker_yes  region_northeast  region_northwest  region_southeast  \
0              1                 0                 0                 0   
1              0                 0                 0                 1   
2              0                 0                 0                 1   
3              0                 0                 1                 0   
4              0                 0                 1                 0   
...          ...               ...               ...               ...   
1333           0                 0                 1                 0   
1334           0                 1                 0                 0   
1335           0                 0                 0                 1   
1336           0                 0                 0                 0   
1337           1                 0                 1                 0   

      region_southwest  
0                    1  
1                    0  
2                    0  
3                    0  
4                    0  
...                ...  
1333                 0  
1334                 0  
1335                 0  
1336                 1  
1337                 0  

[1338 rows x 12 columns]

In [7]:
#creating features and labels
X=encoded_data.drop('charges', axis=1)
y=encoded_data['charges']
X.head(), y.head()

(   age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes  \
 0   19  27.900         0           1         0          0           1   
 1   18  33.770         1           0         1          1           0   
 2   28  33.000         3           0         1          1           0   
 3   33  22.705         0           0         1          1           0   
 4   32  28.880         0           0         1          1           0   
 
    region_northeast  region_northwest  region_southeast  region_southwest  
 0                 0                 0                 0                 1  
 1                 0                 0                 1                 0  
 2                 0                 0                 1                 0  
 3                 0                 1                 0                 0  
 4                 0                 1                 0                 0  ,
 0    16884.92400
 1     1725.55230
 2     4449.46200
 3    21984.47061
 4     3866.85520
 

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=100)

In [10]:
len(X),len(X_train),len(X_test)

(1338, 936, 402)

In [11]:
len(y),len(y_train),len(y_test)

(1338, 936, 402)

In [13]:
#create a model
tf.random.set_seed(100)
model_1=tf.keras.Sequential()
model_1.add(tf.keras.layers.Dense(10))
model_1.add(tf.keras.layers.Dense(1))

In [14]:
#compile the model
model_1.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])

In [17]:
#fit the model
model_1.fit(X_train,y_train,epochs=1000)

Epoch 1/1000
30/30 [==============================] - 2s 24ms/step - loss: 7345.7485 - mae: 7345.7485
Epoch 2/1000
30/30 [==============================] - 1s 17ms/step - loss: 7327.5806 - mae: 7327.5806
Epoch 3/1000
30/30 [==============================] - 0s 11ms/step - loss: 7151.1460 - mae: 7151.1460
Epoch 4/1000
30/30 [==============================] - 1s 16ms/step - loss: 7242.1323 - mae: 7242.1323
Epoch 5/1000
30/30 [==============================] - 0s 10ms/step - loss: 7190.4478 - mae: 7190.4478
Epoch 6/1000
30/30 [==============================] - 0s 13ms/step - loss: 7439.8452 - mae: 7439.8452
Epoch 7/1000
30/30 [==============================] - 1s 17ms/step - loss: 7201.1177 - mae: 7201.1177
Epoch 8/1000
30/30 [==============================] - 1s 15ms/step - loss: 7437.0322 - mae: 7437.0322
Epoch 9/1000
30/30 [==============================] - 0s 14ms/step - loss: 7299.4272 - mae: 7299.4272
Epoch 10/1000
30/30 [==============================] - 0s 12ms/step - loss: 7097.4

In [18]:
model_1.evaluate(X_test,y_test)

13/13 [==============================] - 1s 6ms/step - loss: 5435.0205 - mae: 5435.0205


[5435.0205078125, 5435.0205078125]

In [21]:
y_pred=model_1.predict(X_test)
y_pred

13/13 [==============================] - 0s 4ms/step


array([[  827.1071  ],
       [ 1603.2228  ],
       [ 4014.6125  ],
       [  138.2566  ],
       [17195.97    ],
       [26055.281   ],
       [ 8908.781   ],
       [ 1038.1072  ],
       [20548.785   ],
       [ 8981.82    ],
       [ 8348.525   ],
       [ 1694.778   ],
       [ 6489.31    ],
       [ 1602.1637  ],
       [ 4760.6777  ],
       [21420.71    ],
       [ 6487.4985  ],
       [ 7742.6006  ],
       [ 2931.867   ],
       [10175.967   ],
       [ 7843.4536  ],
       [  -90.062965],
       [ 3186.2722  ],
       [22592.004   ],
       [ 7792.6     ],
       [22236.035   ],
       [ 2960.6868  ],
       [27589.533   ],
       [22122.867   ],
       [ 7773.308   ],
       [11112.903   ],
       [  354.10306 ],
       [27276.287   ],
       [18271.707   ],
       [ 4263.558   ],
       [ 7104.6562  ],
       [ 3729.7427  ],
       [22736.475   ],
       [ 1699.3032  ],
       [26855.998   ],
       [ 3837.9692  ],
       [ 7034.8647  ],
       [ 1826.749   ],
       [ 40

In [20]:
tf.metrics.MAE(y_test,y_pred)

<tf.Tensor: shape=(402,), dtype=float32, numpy=
array([12678.936 , 11915.888 , 10082.499 , 13367.785 , 10663.982 ,
       16219.735 ,  8364.11  , 12467.936 , 12564.297 ,  8358.14  ,
        8430.066 , 11829.559 ,  8896.519 , 11916.904 ,  9644.392 ,
       13108.492 ,  8897.141 ,  8538.995 , 10813.332 ,  8336.122 ,
        8519.427 , 13596.1045, 10631.967 , 13874.704 ,  8529.294 ,
       13639.163 , 10792.686 , 17331.182 , 13564.387 ,  8533.038 ,
        8408.429 , 13151.939 , 17101.814 , 11233.682 ,  9928.972 ,
        8698.847 , 10266.113 , 13970.3   , 11825.327 , 16796.592 ,
       10195.577 ,  8720.14  , 11707.944 , 10069.831 , 14135.572 ,
       11572.999 , 11420.852 , 12715.256 , 13101.542 ,  9334.517 ,
        8327.533 , 10347.137 , 10735.242 ,  9500.135 , 10497.941 ,
        8540.961 ,  8662.527 , 13290.468 ,  9964.757 ,  8738.29  ,
       12720.963 , 12511.294 , 11111.173 ,  9361.369 ,  8396.965 ,
       13357.367 , 13932.896 , 10334.664 ,  9138.7705, 15257.74  ,
        9448.9